# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-keda
  description: This component is used to install the KEDA operator
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component









